[package]
name = "sqlite_skim"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.38.0", features = ["loadable_extension", "functions"] }
skim = { version = "3.1.1", features = ["nightly-frizbee"]}
thiserror = "2.0.18"

[lib]
name = "sqlite_skim"
crate-type = ["cdylib"]
